
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: |
    cd src/azureml-studio-modelspec
    python setup.py bdist_wheel
  displayName: 'Create model spec whl file'

- task: PublishBuildArtifacts@1
  displayName: 'Publish model spec whl file to artifacts'
  inputs:
    pathtoPublish: src/azureml-studio-modelspec/dist
    artifactName: whl

- script: |
    cd src/azureml-studio-score
    python setup.py bdist_wheel
  displayName: 'Create score whl file'

- task: PublishBuildArtifacts@1
  displayName: 'Publish score whl file to artifacts'
  inputs:
    pathtoPublish: src/azureml-studio-score/dist
    artifactName: whl
